### ISSUE TITLE
Problem everytime when calling the the translate function of flutter i18n.

### ISSUE THREAD

**Issue by itsbinay** [ilteoood/flutter_i18n#59] opened 2020-01-14 10:17 UTC
```
The method 'getdecodedMap' was called on null.
Receiver: null
Tried calling: getdecodedMap()
```

this error is invoked everytime when I call the FlutterI18n.translate(context,key) function

Snippet of code:
![Screenshot 2020-01-14 at 6 15 44 PM](https://user-images.githubusercontent.com/44058187/72335558-1b8a6500-36fa-11ea-9369-56ec4a3e210a.png)

Error:
![Screenshot 2020-01-14 at 6 16 12 PM](https://user-images.githubusercontent.com/44058187/72335589-293fea80-36fa-11ea-9222-8e7cbc4443e8.png)

**Comment by itsbinay** [comment] 2020-01-15 01:58
This is what the pubspec.yaml looks like

```
name: xxxxxapp
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.12.0+3
  sqflite: ^1.2.0
  path_provider: ^1.5.1
  easy_localization: ^1.3.1
  flutter_i18n: ^0.8.3

  qr_code_scanner: ^0.0.12
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/i18n/en_US.json
    - assets/i18n/zh_CN.json
    - assets/i18n/zh_HK.json
    - assets/images/bgimages/
    - assets/images/logoimage/
    - assets/images/default_banner/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```
This is what the file directory looks like
![Screenshot 2020-01-15 at 9 54 07 AM](https://user-images.githubusercontent.com/44058187/72398162-0b679980-377d-11ea-8a06-cb837527c11b.png)

I have resolved back to trying to use json file so this is what it looks like for now, my en_US.json

```
{
    "logintitle":"User Login",
    "dashboardtitle":"Event",
    "sessiontitle":"Session",
    "checkInTitle":"check in",

    "langSelect":"Please Select Language",
    
    "username":"Username",
    "password":"Password",
    
    "loginbutton":"Log In",
    "checkInButton":"Check In",
    "checkedInButton":"Checked In",
    
    "logout":"Log Out",
    "search":"Search",
    "edit":"Edit",
    "save":"Save",
    "cancel":"Cancel",
 
    "guestList":"Guest List",
    "checkedIn":"Checked-In",
    "walkedIn":"Walked-In",
    "pendingArrival":"Pending Arrival",

    "status":"Status",
    "online":"Wifi Online",
    "offline":"Offline",
    "syncText":"items to sync",

    "profile":"Profile",
    "info":"Basic Info",

    "firstName":"First Name",
    "lastName":"Last Name",
    "company":"Company",
    "department":"Department",
    "jobTitle":"Job Title",
    "email":"Email",
    "mobile":"Mobile",
    "officePhone":"Office Phone",
    "remarks":"Remarks"
}
```

The loading of is exactly as stated in the example, (main.dart) the entry point of the app is as follows:
```
import 'package:flutter/material.dart';
import 'package:flutter_i18n/flutter_i18n_delegate.dart';
import 'package:xxxxxapp/login/login.dart';//
import 'package:flutter_localizations/flutter_localizations.dart';


Future main() async{
  final FlutterI18nDelegate  flutterI18nDelegate = FlutterI18nDelegate(
    useCountryCode: true,
    path: 'assets/i18n',
    fallbackFile: 'en_US',
    forcedLocale: Locale('en','US')
  );

  WidgetsFlutterBinding.ensureInitialized();
  await flutterI18nDelegate.load(Locale('en','US'));
  print("Loaded");
  runApp(MyApp(flutterI18nDelegate));
}

class MyApp extends StatelessWidget{
  final FlutterI18nDelegate flutterI18nDelegate;
  
  MyApp(this.flutterI18nDelegate);
  @override
  Widget build(BuildContext context){
    return new MaterialApp(
      title: 'Login Page',
      home: LoginPage(),
      localizationsDelegates: [
        this.flutterI18nDelegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
    );
  }
}
```

**Comment by ilteoood** [comment] 2020-01-18 21:19
That's really strange. I can't reproduce it with this configuration.
Do you have the same problem with the provided example?

**Comment by itsbinay** [comment] 2020-01-20 06:46
I tried cloning the example and it works perfectly fine but when I do it on my project, it doesn't seem to be working. I am calling the Flutteri18n.translate(context,"key") in another file and was wondering if this was cause I was calling it in different file and tired calling it in the safe file as my main.dart but still get the same error. Could this be a problem of package being old or affected? Is it possible for me to clone this entire repo and path the package into my project to see if it works?

**Comment by ilteoood** [comment] 2020-01-20 07:02
Of course, you can use this project as local dependency as I did with the example project provided.
I don't think is a problem of packaging, otherwise I would have other issues of this kind.
Did you tried a Flutter clean after the assets configuration?

If you can't figure out, I can help you if want to share with me the project with a private repository

**Comment by itsbinay** [comment] 2020-01-21 04:00
Can you help to check this package '.dart' file? I am worried it may not be like how it is.. If it seems fine then maybe I can try to share the project with you and try to locate where the problem may be arising from.

**flutter_i18n.dart**
```
import 'dart:async';
import 'dart:convert';

import 'package:flutter/services.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:flutter/widgets.dart';
import 'package:intl/intl_standalone.dart';
import 'package:yaml/yaml.dart';

import 'message_printer.dart';

class FlutterI18n {
  static RegExp _parameterRegexp = new RegExp("{(.+)}");
  final bool _useCountryCode;
  final String _fallbackFile;
  final String _basePath;
  Locale forcedLocale;

  Locale locale;

  Map<dynamic, dynamic> decodedMap;

  FlutterI18n(this._useCountryCode,
      [this._fallbackFile, this._basePath, this.forcedLocale]);

  Future<bool> load() async {
    try {
      await _loadCurrentTranslation(this.forcedLocale);
    } catch (e) {
      MessagePrinter.debug('Error loading translation $e');
      await _loadFallback();
    }
    return true;
  }

  Future _loadCurrentTranslation(final Locale locale) async {
    this.locale = locale != null ? locale : await _findCurrentLocale();
    MessagePrinter.info("The current locale is ${this.locale}");
    await _loadFile(_composeFileName());
  }

  Future _loadFallback() async {
    try {
      await _loadFile(_fallbackFile);
    } catch (e) {
      MessagePrinter.debug('Error loading translation fallback $e');
      decodedMap = Map();
    }
  }

  Future<void> _loadFile(final String fileName) async {
    try {
      await _decodeFile(fileName, 'json', json.decode);
      MessagePrinter.info("JSON file loaded for $fileName");
    } on Error catch (_) {
      MessagePrinter.debug("Unable to load JSON file for $fileName, I'm trying with YAML");
      await _decodeFile(fileName, 'yaml', loadYaml);
    }
  }

  Future<void> _decodeFile(final String fileName, final String extension,
      final Function decodeFunction) async {
    decodedMap = await rootBundle
        .loadString('$_basePath/$fileName.$extension')
        .then((fileContent) => decodeFunction(fileContent));
  }

  Future<Locale> _findCurrentLocale() async {
    final String systemLocale = await findSystemLocale();
    MessagePrinter.info("The system locale is $systemLocale");
    final List<String> systemLocaleSplitted = systemLocale.split("_");
    final int countryCodeIndex = systemLocaleSplitted.length == 3 ? 2 : 1;
    return Future(() => Locale(
        systemLocaleSplitted[0], systemLocaleSplitted[countryCodeIndex]));
  }

  static String plural(final BuildContext context, final String translationKey,
      final int pluralValue) {
    final FlutterI18n currentInstance = _retrieveCurrentInstance(context);
    final Map<dynamic, dynamic> decodedSubMap =
        _calculateSubmap(currentInstance.decodedMap, translationKey);
    final String correctKey =
        _findCorrectKey(decodedSubMap, translationKey, pluralValue);
    final String parameterName =
        _findParameterName(decodedSubMap[correctKey.split(".").last]);
    return translate(context, correctKey,
        Map.fromIterables([parameterName], [pluralValue.toString()]));
  }

  static String _findCorrectKey(Map<dynamic, dynamic> decodedSubMap,
      String translationKey, final int pluralValue) {
    final List<String> splittedKey = translationKey.split(".");
    translationKey = splittedKey.removeLast();
    List<int> possiblePluralValues = decodedSubMap.keys
        .where((mapKey) => mapKey.startsWith(translationKey))
        .where((mapKey) => mapKey.split("-").length == 2)
        .map((mapKey) => int.tryParse(mapKey.split("-")[1]))
        .where((mapKeyPluralValue) => mapKeyPluralValue != null)
        .where((mapKeyPluralValue) => mapKeyPluralValue <= pluralValue)
        .toList();
    possiblePluralValues.sort();
    final String lastKeyPart =
        "$translationKey-${possiblePluralValues.length > 0 ? possiblePluralValues.last : ''}";
    splittedKey.add(lastKeyPart);
    return splittedKey.join(".");
  }

  static Map<dynamic, dynamic> _calculateSubmap(
      Map<dynamic, dynamic> decodedMap, final String translationKey) {
    final List<String> translationKeySplitted = translationKey.split(".");
    translationKeySplitted.removeLast();
    translationKeySplitted.forEach((listKey) => decodedMap =
        decodedMap != null && decodedMap[listKey] != null
            ? decodedMap[listKey]
            : new Map());
    return decodedMap;
  }

  static String _findParameterName(final String translation) {
    String parameterName = "";
    if (translation != null && _parameterRegexp.hasMatch(translation)) {
      final Match match = _parameterRegexp.firstMatch(translation);
      parameterName = match.groupCount > 0 ? match.group(1) : "";
    }
    return parameterName;
  }

  static Future refresh(
      final BuildContext context, final Locale forcedLocale) async {
    final FlutterI18n currentInstance = _retrieveCurrentInstance(context);
    currentInstance.forcedLocale = forcedLocale;
    await currentInstance._loadCurrentTranslation(forcedLocale);
  }

  static String translate(final BuildContext context, final String key,
      [final Map<String, String> translationParams]) {
    String translation = _translateWithKeyFallback(context, key);
    if (translationParams != null) {
      translation = _replaceParams(translation, translationParams);
    }
    return translation;
  }

  static Locale currentLocale(final BuildContext context) {
    return _retrieveCurrentInstance(context).locale;
  }

  static String _replaceParams(
      String translation, final Map<String, String> translationParams) {
    for (final String paramKey in translationParams.keys) {
      translation = translation.replaceAll(
          new RegExp('{$paramKey}'), translationParams[paramKey]);
    }
    return translation;
  }

  static String _translateWithKeyFallback(
      final BuildContext context, final String key) {
    final Map<dynamic, dynamic> decodedStrings =
        _retrieveCurrentInstance(context).decodedMap;
    String translation = _decodeFromMap(decodedStrings, key);
    if (translation == null) {
      MessagePrinter.debug("**$key** not found");
      translation = key;
    }
    return translation;
  }

  static FlutterI18n _retrieveCurrentInstance(BuildContext context) {
    return Localizations.of<FlutterI18n>(context, FlutterI18n);
  }

  static String _decodeFromMap(
      Map<dynamic, dynamic> decodedStrings, final String key) {
    final Map<dynamic, dynamic> subMap = _calculateSubmap(decodedStrings, key);
    final String lastKeyPart = key.split(".").last;
    return subMap[lastKeyPart];
  }

  String _composeFileName() {
    return "${locale.languageCode}${_composeCountryCode()}";
  }

  String _composeCountryCode() {
    String countryCode = "";
    if (_useCountryCode && locale.countryCode != null) {
      countryCode = "_${locale.countryCode}";
    }
    return countryCode;
  }
}
```

**flutter_i18n_delegate.dart**

```
library flutter_i18n;

import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter_i18n/message_printer.dart';

import 'flutter_i18n.dart';

class FlutterI18nDelegate extends LocalizationsDelegate<FlutterI18n> {
  final bool useCountryCode;
  final String fallbackFile;
  final String path;
  final Locale forcedLocale;
  static FlutterI18n _currentTranslationObject;

  FlutterI18nDelegate(
      {this.useCountryCode = false,
      this.fallbackFile,
      this.path = "assets/flutter_i18n",
      this.forcedLocale});

  @override
  bool isSupported(final Locale locale) {
    return true;
  }

  @override
  Future<FlutterI18n> load(final Locale locale) async {
    MessagePrinter.info("New locale: $locale");
    if (FlutterI18nDelegate._currentTranslationObject == null ||
        FlutterI18nDelegate._currentTranslationObject.locale != locale) {
      FlutterI18nDelegate._currentTranslationObject =
          FlutterI18n(useCountryCode, fallbackFile, path, this.forcedLocale);
      await FlutterI18nDelegate._currentTranslationObject.load();
    }
    return FlutterI18nDelegate._currentTranslationObject;
  }

  @override
  bool shouldReload(final LocalizationsDelegate old) {
    return _currentTranslationObject == null ||
        _currentTranslationObject.forcedLocale == null;
  }
}

```

**Comment by ilteoood** [comment] 2020-01-21 05:33
These packages are right. They differ from the releases one only for the MessagePrinter class

**Comment by itsbinay** [comment] 2020-01-25 12:01
> Of course, you can use this project as local dependency as I did with the example project provided.
> I don't think is a problem of packaging, otherwise I would have other issues of this kind.
> Did you tried a Flutter clean after the assets configuration?
> 
> If you can't figure out, I can help you if want to share with me the project with a private repository

I think i might need your help, I will send you an invite

**Comment by ilteoood** [comment] 2020-01-26 12:37
I've pushed the fix inside your branch.
The problem was the creation of a new MaterialApp for each page, this brings the framework to register new translation delegates for each page.

**Closed by ilteoood** 2020-01-26 12:37 UTC

**Comment by yacineblr** [comment] 2020-02-05 23:10
I have the same problem, what was the fix please ?

**Comment by ilteoood** [comment] 2020-02-06 05:33
He used the material app widget for every page of the app

**Comment by shlima** [comment] 2020-03-03 18:44
@ilteoood could you please provide a human readable exception instead of system null exception ?

**Comment by ilteoood** [comment] 2020-03-03 18:49
@shlima can you make an example? You should not have a null. There can be an error in configuration or a bug in the new version of the library
